# 1Panel 专用编排文件
services:
  app:
    build: .
    container_name: lucky-wheel
    restart: unless-stopped
    ports:
      - "8686:15000"
    volumes:
      - ./config.py:/app/config.py:ro
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
